version: "2"
services:
    cassandra:
        image: cassandra:latest


    innocharacter:
        build: .
        depends_on:
              - cassandra
        command: spark-1.6.0-bin-hadoop2.6/bin/spark-submit --class AuthTwitter.AuthTwitter --master local[2] target/scala-2.10/innoCharacter-assembly-1.0.jar

